
---
# Common variables
ansible_python_interpreter: /usr/bin/python3


project_name: "toranagaTask"  


git_repo: "https://github.com/telexorg/telex_fe.git"  
app_directory: "/var/www/{{ project_name }}"
app_user: ""
app_port: 3000

# Node.js Configuration
nodejs_version: "18"
pm2_app_name: "{{ project_name }}"

ssl_email: "codewithjoshnick@gmail.com"
