
---
environment: staging
git_branch: develop
domain_name: stagingtoranaga.duckdns.org 
enable_debug: true


# Format: /ec2/{environment}/{project-name}/{component}
cloudwatch_log_groups:
  app: "/ec2/staging/{{ project_name }}/app"
  nginx_access: "/ec2/staging/{{ project_name }}/nginx-access"
  nginx_error: "/ec2/staging/{{ project_name }}/nginx-error"

aws_region: "us-east-1"  
